# Generated by Django 2.2.7 on 2020-05-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_poem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.CharField(max_length=3000),
        ),
    ]
