# Generated by Django 2.2.7 on 2020-05-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200513_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(),
        ),
    ]
