# Generated by Django 2.2.7 on 2020-05-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200513_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='content',
        ),
    ]
